services:
  web:
    image: nginx:alpine
    ports:
      - 80:80
    networks:
      - ordsky
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./build:/var/www/ordsky.no:ro

  api:
    image: registry.opheimutvikling.no/ordsky-api:latest
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ALLOWED_ORIGIN=*
      - CORS_POLICY=same-site
      - DB_URL=/app/data/ordsky.db
    volumes:
      - db_data:/app/data
    networks:
      - ordsky
    restart: unless-stopped

volumes:
  db_data:
    driver: local

networks:
  ordsky:
    driver: bridge
